
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-volume-aoi-victoria-metrics-single-1-server-0
  namespace: application-operations-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
        storage: {{ .Values.victoria-metrics.persistentVolume.size  }}
  storageClassName: default
  volumeMode: Filesystem

{{- if .Values.global.tsdb.high_availability.enabled }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-volume-aoi-victoria-metrics-single-2-server-0
  namespace: application-operations-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.victoria-metrics.persistentVolume.size }}
  storageClassName: default
  volumeMode: Filesystem

{{- end }}
