{{- if .Values.alerting.createNamespace.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vmalert-alertmanager-egress
spec:
  podSelector:
    matchLabels:
      app: alertmanager
      app.kubernetes.io/instance: victoria-metrics-alert
      app.kubernetes.io/name: victoria-metrics-alert
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vmalert-alertmanager-ingress
spec:
  podSelector:
    matchLabels:
      app: alertmanager
      app.kubernetes.io/instance: victoria-metrics-alert
      app.kubernetes.io/name: victoria-metrics-alert
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: server
              app.kubernetes.io/instance: victoria-metrics-alert
              app.kubernetes.io/name: victoria-metrics-alert
      ports:
        - port: web
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vmalert-server-egress
spec:
  podSelector:
    matchLabels:
      app: server
      app.kubernetes.io/instance: victoria-metrics-alert
      app.kubernetes.io/name: victoria-metrics-alert
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 6443
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app: alertmanager
              app.kubernetes.io/instance: victoria-metrics-alert
              app.kubernetes.io/name: victoria-metrics-alert
      ports:
        - port: web
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: application-operations-system
          podSelector:
            matchLabels:
              app: server
              app.kubernetes.io/name: victoria-metrics-single
      ports:
        - port: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vmalert-server-ingress
spec:
  podSelector:
    matchLabels:
      app: server
      app.kubernetes.io/instance: victoria-metrics-alert
      app.kubernetes.io/name: victoria-metrics-alert
  policyTypes:
    - Ingress
{{- end }}
