{{- if .Values.alerting.createNamespace.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoria-metrics-alert-config-reloader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-reloader-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-reloader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: config-reloader-role
subjects:
  - kind: ServiceAccount
    name: victoria-metrics-alert-config-reloader
{{- end }}
