name: Upgrade helm charts minor versions
 
on:
  push:
    tags:
      - 'aoi-*.*.*'


jobs:
 upgrade-helm-charts:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
 
     - name: Set up Helm
       uses: azure/setup-helm@v3
       with:
         version: v3.9.2
 
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.10'
      
     - name: Install pyaml
       run: |
         pip3 install pyaml==23.12.0
 
     - name: Install updateCli
       run: |
         curl -sL -o /tmp/updatecli_amd64.deb https://github.com/updatecli/updatecli/releases/download/v0.72.0/updatecli_amd64.deb
         sudo apt install /tmp/updatecli_amd64.deb
 
     - name: Run chart bumper script
       run: |
         python scripts/chart_bumper.py
         rm -f manifest.yaml
 
     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v6
       with:
         commit-message: "feat: upgrade helm charts"
         title: "chore: upgrade helm charts minor versions"
         body: |
           Automatic upgrade of helm chart minor versions using https://github.com/updatecli/updatecli
         branch: upgrade-helm-charts-minors
         base: main
         reviewers: |
           alex5517
           MathiasFM
